#!/bin/bash
set -e

# Create cache dir if needed
if [ ! -d $OPENSHIFT_REPO_DIR/app/cache ]; then
    mkdir $OPENSHIFT_REPO_DIR/app/cache
fi
chmod -v 777 $OPENSHIFT_REPO_DIR/app/cache

# Create logs dir if needed
if [ ! -d $OPENSHIFT_REPO_DIR/app/logs ]; then
    mkdir $OPENSHIFT_REPO_DIR/app/logs
fi
chmod -v 777 $OPENSHIFT_REPO_DIR/app/logs

cd $OPENSHIFT_REPO_DIR
if [ ! -d $OPENSHIFT_REPO_DIR/composer.phar ]; then
     curl -sS https://getcomposer.org/installer | php -- --install-dir=$OPENSHIFT_REPO_DIR
else
    $OPENSHIFT_REPO_DIR/composer.phar self-update
fi
